### ISSUE TITLE
401 Unauthorized 

### ISSUE THREAD

**Issue by dxomaster** [imrabti/tvshowtime-plex#25]
Worked fine until the 1.1.3.2700 update, now I'm getting 401 Unauthorized error.
Here's the log:
 :::  TVShowTime-Plex (V1.0.3)  :::
15:06 INFO  - Starting ApplicationLauncher v1.0.3-RELEASE on .... with PID 80
16 (C:\Users...\Desktop\tvshowtime-plex-1.0.3\tvshowtimeplex.jar started by ... in C:\Users...\Desktop\tvshowtime-plex-1.0.3)
15:06 INFO  - No active profile set, falling back to default profiles: default
15:06 INFO  - Started ApplicationLauncher in 4.318 seconds (JVM running for 5.35
2)
15:06 INFO  - AccessToken loaded from file with success : AccessToken{access_tok
en='779fb593e652dc406b879a7213d8f08b'}
15:06 ERROR - Error during marking episodes as watched.
15:06 ERROR - 401 Unauthorized

Tried reauthorizing by deleting the AccessToken - no luck.

**Comment by jun6lee** [comment]
I am getting this too. 

One notable thing though, if I manually run it in terminal from the directory it is situated, it works. 

cd /Applications/tvshowtime-plex-1.0.4
java -jar tvshowtimeplex.jar 
**Success.**

from anywhere else:
java -jar /Applications/tvshowtime-plex-1.0.4/tvshowtimeplex.jar 
**Unauthorised 401**

[I'm on OSX]

**Comment by imrabti** [comment]
Sorry for the late answer I have been very busy lately. 

I found what causes the issues, it appears that starting from Plex Media Server 1.1 a token is required for the communication to succeed with PMS, so in the configuration file you have to put your token in in the property **nuvola.pms.token**, in the README I explain how to get the value of the token.

I have updated the README to mention that is property is required, because before PMS 1.1 this property was only required when you multiple users in your PMS. Later I'll release a new version that checks if the token is provided or not.

Can you please confirm that this did fix your problem.

**Comment by dxomaster** [comment]
That did in fact fix it. Thank you! I was starting to lose hope

**Comment by Dhop84** [comment]
Sorry to jump in on this but, I'm desperate to no if this will work on a seagate personal cloud installed version of plex?

**Comment by imrabti** [comment]
No problem, the application is written with Java 8, if you can install Java 8 JRE in your Seagate Personal Cloud then it will work.

**Comment by Dhop84** [comment]
OK cool, are you familiar with the seagate personal cloud?

**Comment by imrabti** [comment]
I have never used Seagate personal Cloud, but if it run linux and is has either ARM or Intel CPU you can install on it Java easily.
